# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivechat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hivechat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehivechat.proto\x12\x08hivechat\"|\n\x0b\x43hatMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x12\x13\n\x0borigin_node\x18\x06 \x01(\t\"V\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x0f\n\x07node_id\x18\x04 \x01(\t\"<\n\x12SendMessageRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.hivechat.ChatMessage\"%\n\x12GetMessagesRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\">\n\x13GetMessagesResponse\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.hivechat.ChatMessage\"*\n\x10HeartbeatRequest\x12\x16\n\x0esender_node_id\x18\x01 \x01(\t\"3\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\"R\n\x10ReplicateRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.hivechat.ChatMessage\x12\x16\n\x0esource_node_id\x18\x02 \x01(\t2\xa5\x01\n\x10MessagingService\x12\x45\n\x0bSendMessage\x12\x1c.hivechat.SendMessageRequest\x1a\x18.hivechat.StatusResponse\x12J\n\x0bGetMessages\x12\x1c.hivechat.GetMessagesRequest\x1a\x1d.hivechat.GetMessagesResponse2\x97\x01\n\x0c\x46\x61ultService\x12\x44\n\tHeartbeat\x12\x1a.hivechat.HeartbeatRequest\x1a\x1b.hivechat.HeartbeatResponse\x12\x41\n\tReplicate\x12\x1a.hivechat.ReplicateRequest\x1a\x18.hivechat.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivechat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=28
  _globals['_CHATMESSAGE']._serialized_end=152
  _globals['_STATUSRESPONSE']._serialized_start=154
  _globals['_STATUSRESPONSE']._serialized_end=240
  _globals['_SENDMESSAGEREQUEST']._serialized_start=242
  _globals['_SENDMESSAGEREQUEST']._serialized_end=302
  _globals['_GETMESSAGESREQUEST']._serialized_start=304
  _globals['_GETMESSAGESREQUEST']._serialized_end=341
  _globals['_GETMESSAGESRESPONSE']._serialized_start=343
  _globals['_GETMESSAGESRESPONSE']._serialized_end=405
  _globals['_HEARTBEATREQUEST']._serialized_start=407
  _globals['_HEARTBEATREQUEST']._serialized_end=449
  _globals['_HEARTBEATRESPONSE']._serialized_start=451
  _globals['_HEARTBEATRESPONSE']._serialized_end=502
  _globals['_REPLICATEREQUEST']._serialized_start=504
  _globals['_REPLICATEREQUEST']._serialized_end=586
  _globals['_MESSAGINGSERVICE']._serialized_start=589
  _globals['_MESSAGINGSERVICE']._serialized_end=754
  _globals['_FAULTSERVICE']._serialized_start=757
  _globals['_FAULTSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
