# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivechat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hivechat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehivechat.proto\x12\x08hivechat\"<\n\x0fTimeSyncRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x18\n\x10\x63lient_send_time\x18\x02 \x01(\x01\"Y\n\x10TimeSyncResponse\x12\x18\n\x10\x63lient_send_time\x18\x01 \x01(\x01\x12\x13\n\x0bserver_time\x18\x02 \x01(\x01\x12\x16\n\x0eserver_node_id\x18\x03 \x01(\x05\x32S\n\x0fTimeSyncService\x12@\n\x07GetTime\x12\x19.hivechat.TimeSyncRequest\x1a\x1a.hivechat.TimeSyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivechat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESYNCREQUEST']._serialized_start=28
  _globals['_TIMESYNCREQUEST']._serialized_end=88
  _globals['_TIMESYNCRESPONSE']._serialized_start=90
  _globals['_TIMESYNCRESPONSE']._serialized_end=179
  _globals['_TIMESYNCSERVICE']._serialized_start=181
  _globals['_TIMESYNCSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
